class PrefectureType < ActiveHash::Base
  include ActiveHash::Enum
  include ActiveHash::Associations
  belongs_to :region_area
  
  self.data = [
{code: '01', name: '北海道', region_code: '01'},
{code: '02', name: '青森県', region_code: '02'},
{code: '03', name: '岩手県', region_code: '02'},
{code: '04', name: '宮城県', region_code: '03'},
{code: '05', name: '秋田県', region_code: '02'},
{code: '06', name: '山形県', region_code: '03'},
{code: '07', name: '福島県', region_code: '03'},
{code: '08', name: '茨城県', region_code: '04'},
{code: '09', name: '栃木県', region_code: '04'},
{code: '10', name: '群馬県', region_code: '04'},
{code: '11', name: '埼玉県', region_code: '04'},
{code: '12', name: '千葉県', region_code: '04'},
{code: '13', name: '東京都', region_code: '04'},
{code: '14', name: '神奈川県', region_code: '04'},
{code: '15', name: '新潟県', region_code: '05'},
{code: '16', name: '富山県', region_code: '06'},
{code: '17', name: '石川県', region_code: '06'},
{code: '18', name: '福井県', region_code: '06'},
{code: '19', name: '山梨県', region_code: '04'},
{code: '20', name: '長野県', region_code: '05'},
{code: '21', name: '岐阜県', region_code: '07'},
{code: '22', name: '静岡県', region_code: '07'},
{code: '23', name: '愛知県', region_code: '07'},
{code: '24', name: '三重県', region_code: '07'},
{code: '25', name: '滋賀県', region_code: '08'},
{code: '26', name: '京都府', region_code: '08'},
{code: '27', name: '大阪府', region_code: '08'},
{code: '28', name: '兵庫県', region_code: '08'},
{code: '29', name: '奈良県', region_code: '08'},
{code: '30', name: '和歌山県', region_code: '08'},
{code: '31', name: '鳥取県', region_code: '09'},
{code: '32', name: '島根県', region_code: '09'},
{code: '33', name: '岡山県', region_code: '09'},
{code: '34', name: '広島県', region_code: '09'},
{code: '35', name: '山口県', region_code: '09'},
{code: '36', name: '徳島県', region_code: '10'},
{code: '37', name: '香川県', region_code: '10'},
{code: '38', name: '愛媛県', region_code: '10'},
{code: '39', name: '高知県', region_code: '10'},
{code: '40', name: '福岡県', region_code: '11'},
{code: '41', name: '佐賀県', region_code: '11'},
{code: '42', name: '長崎県', region_code: '11'},
{code: '43', name: '熊本県', region_code: '11'},
{code: '44', name: '大分県', region_code: '11'},
{code: '45', name: '宮崎県', region_code: '11'},
{code: '46', name: '鹿児島県', region_code: '11'},
{code: '47',  name: '沖縄県', region_code: '12'},
  ]

  enum_accessor :prefecture_type
end
